### ISSUE TITLE
`profit` and `profit-worker` slow startup

### ISSUE THREAD

**Issue by krystophny** [redmod-team/profit#100]
At the moment, `profit` and related scripts take too long to start. This should be fixed by cleverer imports in `__init__.py` and possibly other methods.

**Comment by Rykath** [comment]
On my machine `import profit` takes about `1s`
Using [tuna](https://github.com/nschloe/tuna) the main culprits are identified as:
* `numpy = 107 ms`
* `sklearn = 140 ms`
* `paramz (GPy) = 130 ms`
* `pylab (GPy) = 217 ms`
* `IPython (GPy) = 231 ms`

**Comment by Rykath** [comment]
Improvement by about 50% by moving `GPy` in `profit.sur.gaussian_process`
[Rykath/profit/speed](https://github.com/Rykath/profit/commit/2336e00dffd4c74c8ba1851aa73a017dd5dc0afd)

**Comment by Rykath** [comment]
Another possibility for improving the speed of a small simulation (e.g. `mockup`) would be an `InternalRunner` which directly runs the simulation (without spawning a subprocess for the `Worker`).
Should I implement that?

**Comment by krystophny** [comment]
Yes! This would also be very important for testing Monte Carlo methods runs with many points quickly. There is also a way to call Python functions directly as a simulation without starting any external process, right?
