### ISSUE TITLE
`interface.npy` remains in folder, should be removed after run (?)

### ISSUE THREAD

**Issue by krystophny** [redmod-team/profit#103]

**Comment by Rykath** [comment]
Currently `interface.npy` is removed when calling `profit clean` along with the logs, the generated slurm-script and any remaining run directories.
For reasons of symmetry, the `Interface` is cleaned along with the `Runner`.
We could of course clean the `Runner` automatically after `profit run` (possibly while keeping the logfiles until `clean`)

**Comment by krystophny** [comment]
I see. Yes, cleaning the `Runner` after `run` is a good thing to do, except for cases where this information is needed later. (also run folders are removed automatically, so why not that file too). Generally, it would be best if we have a state that is "as clean as possible" after run, but with collected output.txt still not deleted (dangerous to run `clean` for this reason)
