### ISSUE TITLE
Fit does not work for small length scales

### ISSUE THREAD

**Issue by Rykath** [redmod-team/profit#106]
I can't get the `fit` to work for the new data generated with `GORILLA`.

**Version:** the tests were conducted using the latest (as of 2021-04-24) version of `mkendler` as seen in PR #97. In previous versions the fit also sometimes produced a similar result.

This bug might be related to #99. It might even be that this bug is actually responsible for the behavior seen in #99 and not the logarithmic scale.

# output of `fit` - convergence seems to be a problem

<details>
<summary> no configuration </summary>

```
Initial hyperparameters:
length_scale: [0.00151388]
sigma_n: [0.00024184]
sigma_f: [0.00634512]
Optimized hyperparameters:
length_scale: [21.10524403]
sigma_n: [0.01127425]
sigma_f: [0.08146067]
```

</details>
<details>
<summary> configuring 2 length scales </summary>

```
Initial hyperparameters:
length_scale: [0.001  0.0001]
sigma_n: [0.00024184]
sigma_f: [0.00634512]
Optimized hyperparameters:
length_scale: [34.29999082 28.57668733]
sigma_n: [0.01127386]
sigma_f: [0.0814779]
```
</details>

# Reduction to one dimension
No inital `length_scale` specified, just one input variable, one output variable

<details>
<summary> fit output looks better </summary>

```
Initial hyperparameters:
length_scale: [0.00143508]
sigma_n: [5.18076353e-08]
sigma_f: [1.38748647e-06]
Optimized hyperparameters:
length_scale: [0.00182629]
sigma_n: [3.97746379e-08]
sigma_f: [7.6791768e-08]
```

</details>
<details>
<summary> result </summary>

![image](https://user-images.githubusercontent.com/18230626/115955273-c856b300-a4f5-11eb-8c6c-250e7b329624.png)

</details>

# Data

<details>
<summary> reduced to 1D </summary>

**input**
```
# nu_star
5.500000000000000548e-03
3.250000000000000284e-03
7.750000000000000812e-03
2.125000000000000153e-03
6.625000000000000680e-03
4.375000000000000416e-03
8.875000000000000944e-03
1.562500000000000087e-03
6.062500000000001048e-03
3.812500000000000350e-03
8.312500000000000444e-03
2.687500000000000219e-03
7.187500000000000312e-03
4.937500000000000049e-03
9.437500000000001443e-03
1.281250000000000054e-03
5.781250000000000798e-03
3.531250000000000534e-03
8.031250000000000194e-03
2.406250000000000402e-03
```

**output**
```
# D11
7.232595332146684520e-06
7.626592467180592352e-06
1.008375721371916446e-05
9.751873982459288823e-06
6.427973623514244548e-06
6.727557691294112411e-06
6.422614234207888881e-06
6.253991403170845712e-06
6.546003910961603981e-06
6.959192715269715775e-06
7.324520607679214362e-06
7.952616716490858097e-06
7.800422060347728914e-06
7.480339311007465075e-06
1.143475493108907343e-05
9.034020210949410081e-06
7.072863504479973163e-06
7.024873569713297894e-06
9.595086251789200965e-06
8.159805847859729049e-06
```

</details>

# Rescaling the variables
I tried rescaling both variables with `new = old / old.mean()` and this actually gives meaningful results (in the 1D case)!

<details>
<summary> fit output </summary>

```
Initial hyperparameters:
length_scale: [0.27722608]
sigma_n: [0.00660342]
sigma_f: [0.17684961]
Optimized hyperparameters:
length_scale: [1.52715434]
sigma_n: [0.1635188]
sigma_f: [1.22208624]
```

</details>
<details>
<summary> result </summary>

![image](https://user-images.githubusercontent.com/18230626/115955700-7b281080-a4f8-11eb-95ff-61438136d3af.png)

</details>

using the same approach in 2D works as well, although the fit is *too good* in this case.

<details>
<summary> result 2D </summary>

![image](https://user-images.githubusercontent.com/18230626/115955900-d3abdd80-a4f9-11eb-9cc6-12d2468cc216.png)

</details>

**Comment by krystophny** [comment]
Related to https://github.com/SheffieldML/GPy/issues/862 in GPy. Small output values are swallowed by hard-coded noise (nugget regularization) `sig2n = 1e-8` so output smaller than  `sig_n = 1e-2` is discarded as noise. Same issue in GPyTorch, which even has default nugget `sig2n = 1e-4` which means `sig_n = 1e-2` !
