### ISSUE TITLE
Consistent definition of sigma_f and sigma_n

### ISSUE THREAD

**Issue by manal44** [redmod-team/profit#42]
In proFit, the hyperparameter vector used is: _**[ l=length-scale , sigma^2 = (sigma_n/sigma_f)^2 ]**_  in order to normalize.

Adapt the written functions to this definition:

1. Replace _**l^2**_ by _**l**_ in the functions' arguments.
2. Add a documentation for _**sigma**_ .
3. Add an indication about the choice of **_sigma_f_** (ex: **_sigma_f_** always equal to **_1_**) since it isn't a parameter of the kernel functions.
4. Handle the evantual different values for the same variable **_sigma_f_** given that it becomes an implicit argument for the functions which build the Covariance Matrices **_K(X_test,X_test)_** ; **_K(X_test,X_training)_** ; **_K(X_training,X_training)_** .

**Comment by krystophny** [comment]
Is this now consistenst @mkendler ?

**Comment by mkendler** [comment]
This is consistent, as we use `sigma_f` and `sigma_n` as explicit arguments now.
