### ISSUE TITLE
Implement Active learning

### ISSUE THREAD

**Issue by mkendler** [redmod-team/profit#58]
- [x] create a standardized interface between 'run' and surrogates' active learning
- [x] create actual Active Learning process (fills input.txt with points, that contribute the most information)
- [ ] create test cases and benchmark

**Comment by krystophny** [comment]
See https://github.com/BaptisteRubino/modified-active-hyperlearning for Baptiste's modified Matlab version and https://github.com/redmod-team/profit/blob/master/profit/draft/ for his Python code.
