### ISSUE TITLE
Support relative symbolic links

### ISSUE THREAD

**Issue by krystophny** [redmod-team/profit#82]

**Comment by Rykath** [comment]
From: https://stackoverflow.com/questions/4187210/convert-relative-symbolic-links-to-absolute-symbolic-links

```
find ./ -type l -execdir bash -c 'ln -sfn "$(readlink -f "$0")" "$0"' {} \;
```

With this command we can replace all relative symbolic links in the template folder with absolute ones, which should be easier to copy. Additionally the `copytree` has an `symlink` argument which also needs to be set true.

**Comment by Rykath** [comment]
Does not work on OSX!
Maybe implement the idea directly in python? E.g. with `os.path` or `pathlib`?

**Comment by krystophny** [comment]
As a quick fix one could use macports findutils (https://ports.macports.org/port/findutils) and then call `gfind` or `/opt/local/libexec/gnubin/find`.
